apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: zookeeper
  clusterIP: None  # Headless service
  selector:
    app: zookeeper
