apiVersion: v1
kind: ConfigMap
metadata:
  name: transcoding-config
data:
  appsettings.json: |
    {
      "Logging": {
          "LogLevel": {
              "Default": "Information",
              "Microsoft.AspNetCore": "Warning"
          }
      },
      "AllowedHosts": "*",
      "Kestrel": {
          "EndpointDefaults": {
              "Protocols": "Http2"
          }
      },
      "Minio": {
          "InternalEndpoint": "minio:9000",
          "ExternalEndpoint": "minio.video-streaming.com",
          "AccessKey": "L6kAAtB9vgRNXr4ICDzG",
          "SecretKey": "BHiP96IV5q83yIbofU1MS4tSDYVGHDUkeY31GfIg"
      },
      "Kafka": {
          "BootstrapServers": "kafka:9092",
          "GroupId": "transcoding-service"
      },
      "MetadataService": {
          "Url": "http://videometadata-service:80"
      }
    }


