apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque  # Loại Secret thông thường
data:
  mongodb-root-username: YWRtaW4=                  # "admin" encoded base64
  mongodb-root-password: cGFzc3dvcmRAMTIz  # "password@123" encoded base64
  mongodb-password: cGFzc3dvcmRAMTIz      # Có thể dùng chung hoặc khác với root password
  mongodb-auth-service-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkJTQwMTIzQG1vbmdvZGI6MjcwMTcvYXV0aC1zZXJ2aWNlP2F1dGhTb3VyY2U9YWRtaW4=
  mongodb-user-service-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkJTQwMTIzQG1vbmdvZGI6MjcwMTcvdXNlci1zZXJ2aWNlP2F1dGhTb3VyY2U9YWRtaW4=
  mongodb-videometadata-service-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkJTQwMTIzQG1vbmdvZGI6MjcwMTcvdmlkZW9tZXRhZGF0YS1zZXJ2aWNlP2F1dGhTb3VyY2U9YWRtaW4=
