
name: video-streaming

services:

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: MinIO
    ports:
      - '8000:9000'
      - '8001:9001'
    volumes:
      - ./MinIO-data/data:/data  # Thư mục local để chứa file
      # - ./config:/root/.minio  # Lưu trữ cấu hình
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin@123
      - MINIO_DEFAULT_BUCKETS=files
    networks:
      - video-streaming

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - video-streaming

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - video-streaming

#   kafka-ui:
#     image: provectuslabs/kafka-ui:latest
#     container_name: kafka-ui
#     restart: always
#     depends_on:
#       - kafka
#     ports:
#       - "8080:8080"
#     environment:
#       KAFKA_CLUSTERS_0_NAME: local
#       KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
#     networks:
#       - video-streaming

networks:
  video-streaming:
    name: video-streaming
    driver: bridge