apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      containers:
      - name: streaming-service
        image: vinhtin/streaming-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: streaming-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: streaming-secrets
              key: ConnectionStrings__DefaultConnection
      volumes:
        - name: streaming-volume
          configMap:
            name: transcoding-config
      
