apiVersion: apps/v1
kind: Deployment
metadata:
  name: videoupload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videoupload-service
  template:
    metadata:
      labels:
        app: videoupload-service
    spec:
      containers:
      - name: videoupload-service
        image: vinhtin/videoupload-service:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: videoupload-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: videoupload-secrets
              key: ConnectionStrings__DefaultConnection
      volumes:
        - name: videoupload-volume
          configMap:
            name: videoupload-config
      
